[package]
name = "hilang"
version = "0.2.2"
edition = "2024"
description = "A small programming language"
license = "MIT"
readme = "README.md"
repository = "https://github.com/mushitoriami/hilang"

[dependencies]
kohaku = "=0.1.5"
suzuran = "0.1.1"
